/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Booking = IDL.Record({
  'status' : IDL.Text,
  'bookingId' : IDL.Nat,
  'preferredDate' : IDL.Text,
  'createdTimestamp' : Time,
  'poojaId' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'devoteeName' : IDL.Text,
});
export const Pooja = IDL.Record({
  'fee' : IDL.Nat,
  'descriptionEnglish' : IDL.Text,
  'timing' : IDL.Text,
  'descriptionMalayalam' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'availableDays' : IDL.Vec(IDL.Text),
  'poojaId' : IDL.Nat,
  'nameMalayalam' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const User = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'registeredAt' : Time,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllPoojas' : IDL.Func([], [IDL.Vec(Pooja)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOptedInUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserNotificationPreference' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'publishNotification' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'requestOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'setNotificationPreference' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'status' : IDL.Text,
    'bookingId' : IDL.Nat,
    'preferredDate' : IDL.Text,
    'createdTimestamp' : Time,
    'poojaId' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'devoteeName' : IDL.Text,
  });
  const Pooja = IDL.Record({
    'fee' : IDL.Nat,
    'descriptionEnglish' : IDL.Text,
    'timing' : IDL.Text,
    'descriptionMalayalam' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'availableDays' : IDL.Vec(IDL.Text),
    'poojaId' : IDL.Nat,
    'nameMalayalam' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const User = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'registeredAt' : Time,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllPoojas' : IDL.Func([], [IDL.Vec(Pooja)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOptedInUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserNotificationPreference' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'publishNotification' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'requestOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'setNotificationPreference' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };