/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'status' : IDL.Text,
  'bookingId' : IDL.Nat,
  'preferredDate' : IDL.Text,
  'createdTimestamp' : Time,
  'poojaId' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'devoteeName' : IDL.Text,
});
export const Pooja = IDL.Record({
  'fee' : IDL.Nat,
  'descriptionEnglish' : IDL.Text,
  'timing' : IDL.Text,
  'descriptionMalayalam' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'availableDays' : IDL.Vec(IDL.Text),
  'poojaId' : IDL.Nat,
  'nameMalayalam' : IDL.Text,
});
export const Token = IDL.Record({
  'bookedAt' : Time,
  'tokenNumber' : IDL.Nat,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'uploaderName' : IDL.Text,
  'caption' : IDL.Text,
  'blobId' : IDL.Text,
  'mediaType' : IDL.Text,
  'uploadedAt' : Time,
  'uploaderPhone' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const User = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'registeredAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'bookToken' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllPoojas' : IDL.Func([], [IDL.Vec(Pooja)], ['query']),
  'getAllTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOptedInUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTokenByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Token)], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserNotificationPreference' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'publishNotification' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'requestOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'setNotificationPreference' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'status' : IDL.Text,
    'bookingId' : IDL.Nat,
    'preferredDate' : IDL.Text,
    'createdTimestamp' : Time,
    'poojaId' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'devoteeName' : IDL.Text,
  });
  const Pooja = IDL.Record({
    'fee' : IDL.Nat,
    'descriptionEnglish' : IDL.Text,
    'timing' : IDL.Text,
    'descriptionMalayalam' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'availableDays' : IDL.Vec(IDL.Text),
    'poojaId' : IDL.Nat,
    'nameMalayalam' : IDL.Text,
  });
  const Token = IDL.Record({
    'bookedAt' : Time,
    'tokenNumber' : IDL.Nat,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'uploaderName' : IDL.Text,
    'caption' : IDL.Text,
    'blobId' : IDL.Text,
    'mediaType' : IDL.Text,
    'uploadedAt' : Time,
    'uploaderPhone' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const User = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'registeredAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'bookToken' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllPoojas' : IDL.Func([], [IDL.Vec(Pooja)], ['query']),
    'getAllTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOptedInUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTokenByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Token)], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserNotificationPreference' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'publishNotification' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'requestOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'setNotificationPreference' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };