/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : string,
  'bookingId' : bigint,
  'preferredDate' : string,
  'createdTimestamp' : Time,
  'poojaId' : bigint,
  'phoneNumber' : string,
  'devoteeName' : string,
}
export interface Notification {
  'id' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export interface Pooja {
  'fee' : bigint,
  'descriptionEnglish' : string,
  'timing' : string,
  'descriptionMalayalam' : string,
  'nameEnglish' : string,
  'availableDays' : Array<string>,
  'poojaId' : bigint,
  'nameMalayalam' : string,
}
export type Time = bigint;
export interface User {
  'name' : string,
  'phoneNumber' : string,
  'registeredAt' : Time,
}
export interface Token {
  'tokenNumber' : bigint,
  'name' : string,
  'phoneNumber' : string,
  'bookedAt' : Time,
}
export interface _SERVICE {
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllPoojas' : ActorMethod<[], Array<Pooja>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOptedInUsers' : ActorMethod<[], Array<string>>,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUserNotificationPreference' : ActorMethod<[string], boolean>,
  'isRegistered' : ActorMethod<[string], boolean>,
  'publishNotification' : ActorMethod<[string, string], boolean>,
  'requestOTP' : ActorMethod<[string, string], string>,
  'setNotificationPreference' : ActorMethod<[string, boolean], undefined>,
  'submitBooking' : ActorMethod<[string, string, bigint, string], bigint>,
  'updateBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
  'bookToken' : ActorMethod<[string, string], bigint>,
  'getAllTokens' : ActorMethod<[], Array<Token>>,
  'getTokenByPhone' : ActorMethod<[string], [] | [Token]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
