/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : string,
  'bookingId' : bigint,
  'preferredDate' : string,
  'createdTimestamp' : Time,
  'poojaId' : bigint,
  'phoneNumber' : string,
  'devoteeName' : string,
}
export interface GalleryItem {
  'id' : bigint,
  'uploaderName' : string,
  'caption' : string,
  'blobId' : string,
  'mediaType' : string,
  'uploadedAt' : Time,
  'uploaderPhone' : string,
}
export interface Notification {
  'id' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export interface Pooja {
  'fee' : bigint,
  'descriptionEnglish' : string,
  'timing' : string,
  'descriptionMalayalam' : string,
  'nameEnglish' : string,
  'availableDays' : Array<string>,
  'poojaId' : bigint,
  'nameMalayalam' : string,
}
export type Time = bigint;
export interface Token {
  'bookedAt' : Time,
  'tokenNumber' : bigint,
  'name' : string,
  'phoneNumber' : string,
}
export interface User {
  'name' : string,
  'phoneNumber' : string,
  'registeredAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addGalleryItem' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'bookToken' : ActorMethod<[string, string], bigint>,
  'deleteGalleryItem' : ActorMethod<[bigint, string], boolean>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllPoojas' : ActorMethod<[], Array<Pooja>>,
  'getAllTokens' : ActorMethod<[], Array<Token>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOptedInUsers' : ActorMethod<[], Array<string>>,
  'getTokenByPhone' : ActorMethod<[string], [] | [Token]>,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUserNotificationPreference' : ActorMethod<[string], boolean>,
  'isRegistered' : ActorMethod<[string], boolean>,
  'publishNotification' : ActorMethod<[string, string], boolean>,
  'requestOTP' : ActorMethod<[string, string], string>,
  'setNotificationPreference' : ActorMethod<[string, boolean], undefined>,
  'submitBooking' : ActorMethod<[string, string, bigint, string], bigint>,
  'updateBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];